GET http://localhost:5000/
###

GET http://localhost:5000/json

### 
GET https://opentdb.com/api.php?amount=10

###
POST http://localhost:5000/api/flight/book
Content-Type: application/json
{
  "flightid": "12345",
  "passengerid": "67890",
}